[Account]

Value = "rQwKayqFwx5kHUQJ4z4VjA8fQqgD4go4xR"

[SetFlag]

Value = 5

[Sequence]

Value = 79822889

[SigningPubKey]

Value = "0263B92EE3ADC7F644D7CD350452033EFA5EB9340014ECD854A0B6A827D4F61BB4"

[TxnSignature]

Value = "304402200B1488C3D67E1C1B5CBE3A42A6B664F4EDAABAA891DE616B16F4ADB99347F221022045D0FA3BAA49D3B99C77ABF2A60EFE051C2"

[code]

Symbol = "BIGB"

[TransactionMetadata.meta.token]

asset_class = "meme coin"

token_ID = "4249474200000000000000000000000000000000"

description = "BIGBLUEGORILLA was inspired by continually getting ripped off by fees on other meme coins. So we minted our coin on XRPL with a maximum supply of 999666333 and a 0% transaction fee. The world greatest meme coin!!!"

icon = "https://storage.cloud.google.com/bigb20/Bigbluegorilla_icon.png"

name = "BIGBLUEGORILLA"

trust_level = 1

[TransactionMetadata.meta.issuer]

description = "WORLDS BEST MEME COIN!?"

domain = "626967626C7565676F72696C6C612E646576"

icon = "https://storage.cloud.google.com/bigb20/Bigbluegorilla_icon.png"

kyc = true

name = "Joseph Stone"

trust_level = 1

[TransactionMetadata.meta.Signers[0]]

Quorum = 4

[TransactionMetadata.meta.Signers[1]]

SignerWeight = 3

Account = "rnQjw3RFcRQnHXy44bFrei7wyzU6Vfux3S"

SigningPubKey = "0263B92EE3ADC7F644D7CD350452033EFA5EB9340014ECD854A0B6A827D4F61BB4"

TxnSignature = "30440220691DA004033EE39DDEDA368296002B8FD1C8C6F1B18F9041881EDB1B147883EB0220313BBF9E9648A1971C3FEA66238400942402AB08D7190804D7765390FB4FBC09"

[TransactionMetadata.meta.Signers[2]]

SignerWeight = 1

Account = "rNqWdRF7i8JwTgt55njZK9kMxiaWHxR8iY"

SigningPubKey = "0263B92EE3ADC7F644D7CD350452033EFA5EB9340014ECD854A0B6A827D4F61BB4"

TxnSignature = "30440220691DA004033EE39DDEDA368296002B8FD1C8C6F1B18F9041881EDB1B147883EB0220313BBF9E9648A1971C3FEA66238400942402AB08D7190804D7765390FB4FBC09"

[TransactionMetadata.meta.Signers[3]]

SignerWeight = 1

Account = "r49KXVD7bb5uLuHwgK25QAzw7as6jHURKh"

SigningPubKey = "0263B92EE3ADC7F644D7CD350452033EFA5EB9340014ECD854A0B6A827D4F61BB4"

TxnSignature = "30440220691DA004033EE39DDEDA368296002B8FD1C8C6F1B18F9041881EDB1B147883EB0220313BBF9E9648A1971C3FEA66238400942402AB08D7190804D7765390FB4FBC09"

[TransactionMetadata.meta.Validators[0]]

Name = "XRPLF"

Server = "validator.xrpl-labs.com"

Network = "Mainnet"

WssUrl = "wss://xrplcluster.com/"

ApiUrl = "https://xrplcluster.com/"

[TransactionMetadata.meta.Validators[1]]

Name = "Ripple 1"

Server = "https://s1.ripple.com:51234/"

WebSocket = "wss://s1.ripple.com/"

[TransactionMetadata.meta.Validators[2]]

Name = "Ripple 2"

Server = "https://s2.ripple.com:51234/"

WebSocket = "wss://s2.ripple.com/"

[TransactionMetadata.meta.Validators[3]]

Name = "xrplcluster"

Server = "https://xrplcluster.com/"

WebSocket = "https://xrpl.ws/"

[TransactionMetadata.meta.Validators[4]]

name = "xpectar"

RegularKey = "nHUpDEZX5Zy9auiu4yhDmhirNu6PyB1LvzQEL9Mxmqjr818w663q"

WebSocket = "xspectar.com"

[TransactionMetadata.meta.Validators[5]]

name = "xrpscan"

PublicKey = "nHDB2PAPYqF86j9j3c6w1F1ZqwvQfiWcFShZ9Pokg9q4ohNDSkAz"

weblinks = "xrpscan.com"

[TransactionMetadata.metadata[0]]

url = "https://www.bigbluegorilla.dev"

type = "website"

[TransactionMetadata.metadata[1]]

url = "https://twitter.com/BIGBLUEGORILLA_"

type = "socialmedia"

[TransactionMetadata.metadata[2]]

email = "Joseph@bigbluegorilla.dev"

type = "support"

[files]

json_file = "https://github.com/3dogJoe/Bigbluegorilla.json/blob/5fa721a8cced4f2695609850604a441fddd2c118/Bigbluegorilla.json"
