title = "XRPL Bigbluegorilla Token"

description = "Token details for the XRPL Bigbluegorilla Token"

date = "2022-04-01"

[token]

asset_class = "meme coin"

token_ID = "4249474200000000000000000000000000000000"

symbol = "BIGB"

description = "BIGBLUEGORILLA was inspired by continually getting ripped off by fees on other meme coins. So we minted our coin on XRPL with a maximum supply of 999666333 and a 0.00 transaction fees. The Worlds Greatest Meme Coin!"

icon = "https://storage.cloud.google.com/bigbluegorilla-toml/Bigbluegorilla-ICON.png"

name = "BIGBLUEGORILLA"

trust_level = 1

[issuer]

description = "WORLDS BEST MEME COIN!?"

domain = "626967626C7565676F72696C6C612E646576"

icon = "https://storage.cloud.google.com/bigbluegorilla-toml/Bigbluegorilla-ICON.png"

kyc = true

name = "Joseph Stone"

trust_level = 1

[VALIDATORS]

name = xrpscan

Domain = xrpscan.com

Public key = nHDB2PAPYqF86j...okg9q4ohNDSkAz

Sequence = 2

XRPL address = raBce5yMLYDhM6odPgTWfQYLZjWNh35fP1

name = xrpvalidator

Domain = xrpvalidator.ftso.eu

Public key =

nHBdXSF6YHAHSZ...tq8x1XuH6KXKXr

Sequence = 2

XRPL address =

rD6Rc3cKazuUutMCzDteLV6DPg7PkiyRqy

name = ripple

public_key = "nHUXeusfwk61c4xJPneb9Lgy7Ga6DVaVLEyB29ftUdt9k2KxD6Hw"

attestation = "F0D14D7AE4355517A1C3BD626BB78E947178727E7C8F231CE44D83CEC097D9C1545CEFF4B1279357300E4B72705361633BABE40A92310CA326904ED6B155700C"

unl = "https://vl.ripple.com"

[server]

name = "XRPLF"

server_url = "validator.xrpl-labs.com"

network = "Mainnet"

[nodes]

node1 = "wss://xrplcluster.com/"

node2 = "wss://xrpl.ws/"

[signers.signer1]

weight = 3

address = "rnQjw3RFcRQnHXy44bFrei7wyzU6Vfux3S"

[signers.signer2]

weight = 1

address = "rNqWdRF7i8JwTgt55njZK9kMxiaWHxR8iY"

[signers.signer3]

weight = 1

address = "r49KXVD7bb5uLuHwgK25QAzw7as6jHURKh"

[files]

json_file = "https://storage.googleapis.com/bigbluegorilla-toml/config/validators.json"

